// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Persistence.Context;

#nullable disable

namespace Persistence.Migrations
{
    [DbContext(typeof(BaseDbContext))]
    [Migration("20260531121728_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Domain.Entities.Birim", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("AktifMi")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true)
                        .HasColumnName("aktif_mi");

                    b.Property<string>("BirimAdi")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)")
                        .HasColumnName("birim_adi");

                    b.Property<string>("BirimKodu")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("birim_kodu");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("created_date");

                    b.Property<DateTime?>("DeletedDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("deleted_date");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("updated_date");

                    b.HasKey("Id");

                    b.HasIndex("BirimKodu")
                        .IsUnique();

                    b.ToTable("tbl_birimler", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.BirimOnDegerlendirmeRaporu", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CevaplarJson")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("cevaplar_json");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("created_date");

                    b.Property<int>("DegerlendirmeSonucu")
                        .HasColumnType("int")
                        .HasColumnName("degerlendirme_sonucu");

                    b.Property<DateTime?>("DeletedDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("deleted_date");

                    b.Property<string>("DosyaYolu")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("dosya_yolu");

                    b.Property<string>("FormKodu")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)")
                        .HasColumnName("form_kodu");

                    b.Property<string>("Gerekce")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("gerekce");

                    b.Property<int>("KurulUyesiId")
                        .HasColumnType("int")
                        .HasColumnName("kurul_uyesi_id");

                    b.Property<int>("ProjeId")
                        .HasColumnType("int")
                        .HasColumnName("proje_id");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("updated_date");

                    b.HasKey("Id");

                    b.HasIndex("KurulUyesiId");

                    b.HasIndex("ProjeId");

                    b.ToTable("tbl_bapbirim_ondegerlendirme_raporu", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.BirimOnDegerlendirmeUyesi", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Ad")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)")
                        .HasColumnName("ad");

                    b.Property<bool>("AktifMi")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true)
                        .HasColumnName("aktif_mi");

                    b.Property<int>("BirimId")
                        .HasColumnType("int")
                        .HasColumnName("birim_id");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("created_date");

                    b.Property<DateTime?>("DeletedDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("deleted_date");

                    b.Property<string>("Eposta")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("eposta");

                    b.Property<string>("Soyad")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)")
                        .HasColumnName("soyad");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("updated_date");

                    b.HasKey("Id");

                    b.HasIndex("BirimId");

                    b.HasIndex("Eposta");

                    b.ToTable("tbl_bapbirim_ondegerlendirme_uyesi", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.DetayliButce", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Aciklama")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("aciklama");

                    b.Property<string>("ButceKalemi")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("butce_kalemi");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("created_date");

                    b.Property<DateTime?>("DeletedDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("deleted_date");

                    b.Property<int>("ProjeId")
                        .HasColumnType("int")
                        .HasColumnName("proje_id");

                    b.Property<decimal>("TalepEdilenTutar")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("talep_edilen_tutar");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("updated_date");

                    b.HasKey("Id");

                    b.HasIndex("ProjeId");

                    b.ToTable("tbl_bapdetaylibutce", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.DosyaDeposu", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("created_date");

                    b.Property<DateTime?>("DeletedDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("deleted_date");

                    b.Property<string>("DosyaAdi")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("dosya_adi");

                    b.Property<int>("DosyaTipi")
                        .HasColumnType("int")
                        .HasColumnName("dosya_tipi");

                    b.Property<string>("DosyaYolu")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("dosya_yolu");

                    b.Property<int>("SiraNo")
                        .HasColumnType("int")
                        .HasColumnName("sira_no");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("updated_date");

                    b.HasKey("Id");

                    b.HasIndex("DosyaTipi");

                    b.ToTable("tbl_dosya_deposu", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.EkButceTalebi", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("created_date");

                    b.Property<DateTime?>("DeletedDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("deleted_date");

                    b.Property<string>("DosyaYolu")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("dosya_yolu");

                    b.Property<string>("Gerekce")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("gerekce");

                    b.Property<decimal?>("KabulEdilenTutar")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("kabul_edilen_tutar");

                    b.Property<int>("Karar")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0)
                        .HasColumnName("karar");

                    b.Property<DateTime?>("KararTarihi")
                        .HasColumnType("datetime2")
                        .HasColumnName("karar_tarihi");

                    b.Property<int>("ProjeId")
                        .HasColumnType("int")
                        .HasColumnName("proje_id");

                    b.Property<decimal>("TalepEdilenTutar")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("talep_edilen_tutar");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("updated_date");

                    b.HasKey("Id");

                    b.HasIndex("ProjeId");

                    b.ToTable("tbl_bapekbutce_talebi", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.EkSureTalebi", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("created_date");

                    b.Property<DateTime?>("DeletedDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("deleted_date");

                    b.Property<string>("DosyaYolu")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("dosya_yolu");

                    b.Property<string>("Gerekce")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("gerekce");

                    b.Property<int>("Karar")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0)
                        .HasColumnName("karar");

                    b.Property<DateTime?>("KararTarihi")
                        .HasColumnType("datetime2")
                        .HasColumnName("karar_tarihi");

                    b.Property<int>("ProjeId")
                        .HasColumnType("int")
                        .HasColumnName("proje_id");

                    b.Property<int>("TalepEdilenSure")
                        .HasColumnType("int")
                        .HasColumnName("talep_edilen_sure");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("updated_date");

                    b.HasKey("Id");

                    b.HasIndex("ProjeId");

                    b.ToTable("tbl_bapeksure_talebi", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.FormSablonu", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Aciklama")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("aciklama");

                    b.Property<string>("Ad")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("ad");

                    b.Property<bool>("AktifMi")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true)
                        .HasColumnName("aktif_mi");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("created_date");

                    b.Property<DateTime?>("DeletedDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("deleted_date");

                    b.Property<string>("Kod")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)")
                        .HasColumnName("kod");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("updated_date");

                    b.HasKey("Id");

                    b.HasIndex("Kod")
                        .IsUnique();

                    b.ToTable("tbl_form_sablonlari", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.FormSorusu", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CevapTipi")
                        .HasColumnType("int")
                        .HasColumnName("cevap_tipi");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("created_date");

                    b.Property<DateTime?>("DeletedDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("deleted_date");

                    b.Property<int>("FormSablonuId")
                        .HasColumnType("int")
                        .HasColumnName("form_sablonu_id");

                    b.Property<int>("SiraNo")
                        .HasColumnType("int")
                        .HasColumnName("sira_no");

                    b.Property<string>("SoruMetni")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("soru_metni");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("updated_date");

                    b.Property<bool>("ZorunluMu")
                        .HasColumnType("bit")
                        .HasColumnName("zorunlu_mu");

                    b.HasKey("Id");

                    b.HasIndex("FormSablonuId");

                    b.HasIndex("FormSablonuId", "SiraNo");

                    b.ToTable("tbl_form_sorulari", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.Hakem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Ad")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)")
                        .HasColumnName("ad");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("created_date");

                    b.Property<DateTime?>("DeletedDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("deleted_date");

                    b.Property<string>("Eposta")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("eposta");

                    b.Property<string>("Kurum")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)")
                        .HasColumnName("kurum");

                    b.Property<string>("Soyad")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)")
                        .HasColumnName("soyad");

                    b.Property<string>("Telefon")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)")
                        .HasColumnName("telefon");

                    b.Property<string>("Unvan")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)")
                        .HasColumnName("unvan");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("updated_date");

                    b.HasKey("Id");

                    b.HasIndex("Eposta")
                        .IsUnique();

                    b.ToTable("tbl_baphakem", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.Harcama", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Aciklama")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("aciklama");

                    b.Property<string>("BelgeYolu")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("belge_yolu");

                    b.Property<string>("ButceKalemi")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("butce_kalemi");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("created_date");

                    b.Property<DateTime?>("DeletedDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("deleted_date");

                    b.Property<DateTime>("HarcamaTarihi")
                        .HasColumnType("datetime2")
                        .HasColumnName("harcama_tarihi");

                    b.Property<int>("ProjeId")
                        .HasColumnType("int")
                        .HasColumnName("proje_id");

                    b.Property<decimal>("Tutar")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("tutar");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("updated_date");

                    b.HasKey("Id");

                    b.HasIndex("ButceKalemi");

                    b.HasIndex("ProjeId");

                    b.ToTable("tbl_bapharcama", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.HazirMesaj", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("AktifMi")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true)
                        .HasColumnName("aktif_mi");

                    b.Property<string>("Baslik")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("baslik");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("created_date");

                    b.Property<DateTime?>("DeletedDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("deleted_date");

                    b.Property<string>("Icerik")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("icerik");

                    b.Property<string>("Konu")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)")
                        .HasColumnName("konu");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("updated_date");

                    b.HasKey("Id");

                    b.ToTable("tbl_hazir_mesajlar", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.KomisyonKarari", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("created_date");

                    b.Property<DateTime?>("DeletedDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("deleted_date");

                    b.Property<string>("Gerekce")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("gerekce");

                    b.Property<string>("KararMetni")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("karar_metni");

                    b.Property<DateTime>("KararTarihi")
                        .HasColumnType("datetime2")
                        .HasColumnName("karar_tarihi");

                    b.Property<int>("KararTipi")
                        .HasColumnType("int")
                        .HasColumnName("karar_tipi");

                    b.Property<int>("KomisyonUyesiId")
                        .HasColumnType("int")
                        .HasColumnName("komisyon_uyesi_id");

                    b.Property<int>("ProjeId")
                        .HasColumnType("int")
                        .HasColumnName("proje_id");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("updated_date");

                    b.HasKey("Id");

                    b.HasIndex("KomisyonUyesiId");

                    b.HasIndex("ProjeId");

                    b.ToTable("tbl_bapkomisyonu_karar", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.KomisyonUyesi", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Ad")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)")
                        .HasColumnName("ad");

                    b.Property<bool>("AktifMi")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true)
                        .HasColumnName("aktif_mi");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("created_date");

                    b.Property<DateTime?>("DeletedDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("deleted_date");

                    b.Property<string>("Eposta")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("eposta");

                    b.Property<string>("Gorev")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)")
                        .HasColumnName("gorev");

                    b.Property<string>("Soyad")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)")
                        .HasColumnName("soyad");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("updated_date");

                    b.HasKey("Id");

                    b.HasIndex("Eposta")
                        .IsUnique();

                    b.ToTable("tbl_bapkomisyonu", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.LogKaydi", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Controller")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("controller");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("created_date");

                    b.Property<DateTime?>("DeletedDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("deleted_date");

                    b.Property<string>("IpAdresi")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("ip_adresi");

                    b.Property<string>("Islem")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("islem");

                    b.Property<string>("Kullanici")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("kullanici");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("updated_date");

                    b.HasKey("Id");

                    b.HasIndex("CreatedDate");

                    b.ToTable("tbl_log_kaydi", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.Mesaj", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("created_date");

                    b.Property<DateTime?>("DeletedDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("deleted_date");

                    b.Property<string>("Icerik")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("icerik");

                    b.Property<string>("Kimden")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("kimden");

                    b.Property<string>("Kime")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("kime");

                    b.Property<string>("Konu")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)")
                        .HasColumnName("konu");

                    b.Property<bool>("OkunduMu")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false)
                        .HasColumnName("okundu_mu");

                    b.Property<bool>("SilindiMi")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false)
                        .HasColumnName("silindi_mi");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("updated_date");

                    b.HasKey("Id");

                    b.HasIndex("Kimden");

                    b.HasIndex("Kime");

                    b.ToTable("tbl_mesajlar", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.OturumKaydi", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Aciklama")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("aciklama");

                    b.Property<bool>("BasariliMi")
                        .HasColumnType("bit")
                        .HasColumnName("basarili_mi");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("created_date");

                    b.Property<DateTime?>("DeletedDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("deleted_date");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("email");

                    b.Property<string>("IpAdresi")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("ip_adresi");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("updated_date");

                    b.HasKey("Id");

                    b.HasIndex("CreatedDate");

                    b.HasIndex("Email");

                    b.ToTable("tbl_oturum_kaydi", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.ProformaFatura", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("created_date");

                    b.Property<DateTime?>("DeletedDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("deleted_date");

                    b.Property<string>("DosyaYolu")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("dosya_yolu");

                    b.Property<string>("FirmaAdi")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)")
                        .HasColumnName("firma_adi");

                    b.Property<int>("ProjeId")
                        .HasColumnType("int")
                        .HasColumnName("proje_id");

                    b.Property<decimal>("Tutar")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("tutar");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("updated_date");

                    b.HasKey("Id");

                    b.HasIndex("ProjeId");

                    b.ToTable("tbl_bapproformafatura", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.Proje", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("BaslangicTarihi")
                        .HasColumnType("datetime2")
                        .HasColumnName("baslangic_tarihi");

                    b.Property<string>("Baslik")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)")
                        .HasColumnName("baslik");

                    b.Property<DateTime?>("BitisTarihi")
                        .HasColumnType("datetime2")
                        .HasColumnName("bitis_tarihi");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("created_date");

                    b.Property<DateTime?>("DeletedDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("deleted_date");

                    b.Property<int>("Durum")
                        .HasColumnType("int")
                        .HasColumnName("durum");

                    b.Property<string>("Ozet")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("ozet");

                    b.Property<int>("ProjeTipiId")
                        .HasColumnType("int")
                        .HasColumnName("proje_tipi_id");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("updated_date");

                    b.Property<int>("YurutucuUserId")
                        .HasColumnType("int")
                        .HasColumnName("yurutucu_user_id");

                    b.HasKey("Id");

                    b.HasIndex("Durum");

                    b.ToTable("tbl_bapproje", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.ProjeArastirmacisi", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Ad")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)")
                        .HasColumnName("ad");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("created_date");

                    b.Property<DateTime?>("DeletedDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("deleted_date");

                    b.Property<string>("Eposta")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("eposta");

                    b.Property<string>("Gorev")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)")
                        .HasColumnName("gorev");

                    b.Property<decimal>("KatkiOrani")
                        .HasPrecision(5, 2)
                        .HasColumnType("decimal(5,2)")
                        .HasColumnName("katki_orani");

                    b.Property<string>("Kurum")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)")
                        .HasColumnName("kurum");

                    b.Property<int>("ProjeId")
                        .HasColumnType("int")
                        .HasColumnName("proje_id");

                    b.Property<string>("Soyad")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)")
                        .HasColumnName("soyad");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("updated_date");

                    b.HasKey("Id");

                    b.HasIndex("ProjeId");

                    b.HasIndex("ProjeId", "Eposta")
                        .IsUnique();

                    b.ToTable("tbl_bapproje_arastirmacilar", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.ProjeHakem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("CevapTarihi")
                        .HasColumnType("datetime2")
                        .HasColumnName("cevap_tarihi");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("created_date");

                    b.Property<DateTime?>("DavetTarihi")
                        .HasColumnType("datetime2")
                        .HasColumnName("davet_tarihi");

                    b.Property<DateTime?>("DegerlendirmeTarihi")
                        .HasColumnType("datetime2")
                        .HasColumnName("degerlendirme_tarihi");

                    b.Property<DateTime?>("DeletedDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("deleted_date");

                    b.Property<int>("HakemId")
                        .HasColumnType("int")
                        .HasColumnName("hakem_id");

                    b.Property<int>("HakemlikDurumu")
                        .HasColumnType("int")
                        .HasColumnName("hakemlik_durumu");

                    b.Property<int>("ProjeId")
                        .HasColumnType("int")
                        .HasColumnName("proje_id");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("updated_date");

                    b.HasKey("Id");

                    b.HasIndex("HakemId");

                    b.HasIndex("HakemlikDurumu");

                    b.HasIndex("ProjeId");

                    b.HasIndex("ProjeId", "HakemId")
                        .IsUnique();

                    b.ToTable("tbl_projehakem", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.ProjeRaporu", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("created_date");

                    b.Property<DateTime?>("DeletedDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("deleted_date");

                    b.Property<string>("DosyaYolu")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("dosya_yolu");

                    b.Property<DateTime?>("GonderimTarihi")
                        .HasColumnType("datetime2")
                        .HasColumnName("gonderim_tarihi");

                    b.Property<bool?>("HakemOnayi")
                        .HasColumnType("bit")
                        .HasColumnName("hakem_onayi");

                    b.Property<bool>("HakemeGonderildiMi")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false)
                        .HasColumnName("hakeme_gonderildi_mi");

                    b.Property<int>("ProjeId")
                        .HasColumnType("int")
                        .HasColumnName("proje_id");

                    b.Property<int>("RaporKodu")
                        .HasColumnType("int")
                        .HasColumnName("rapor_kodu");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("updated_date");

                    b.HasKey("Id");

                    b.HasIndex("ProjeId");

                    b.HasIndex("ProjeId", "RaporKodu")
                        .IsUnique();

                    b.ToTable("tbl_bapproje_raporu", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.ProjeTipi", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Aciklama")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("aciklama");

                    b.Property<string>("Ad")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)")
                        .HasColumnName("ad");

                    b.Property<bool>("AktifMi")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true)
                        .HasColumnName("aktif_mi");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("created_date");

                    b.Property<DateTime?>("DeletedDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("deleted_date");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("updated_date");

                    b.HasKey("Id");

                    b.HasIndex("Ad")
                        .IsUnique();

                    b.ToTable("tbl_proje_tipleri", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.SorunBildirimi", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("created_date");

                    b.Property<DateTime?>("DeletedDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("deleted_date");

                    b.Property<int>("Durum")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0)
                        .HasColumnName("durum");

                    b.Property<string>("Eposta")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("eposta");

                    b.Property<string>("IpAdresi")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("ip_adresi");

                    b.Property<string>("Konu")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)")
                        .HasColumnName("konu");

                    b.Property<string>("Mesaj")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("mesaj");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("updated_date");

                    b.HasKey("Id");

                    b.ToTable("tbl_sorun_bildirimleri", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.SorunYaniti", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("created_date");

                    b.Property<DateTime?>("DeletedDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("deleted_date");

                    b.Property<int>("SorunBildirimiId")
                        .HasColumnType("int")
                        .HasColumnName("sorun_bildirimi_id");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("updated_date");

                    b.Property<string>("Yanit")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("yanit");

                    b.Property<string>("Yanitlayan")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("yanitlayan");

                    b.HasKey("Id");

                    b.HasIndex("SorunBildirimiId");

                    b.ToTable("tbl_sorun_yanitlari", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.TeknikSartname", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Aciklama")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("aciklama");

                    b.Property<string>("Baslik")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)")
                        .HasColumnName("baslik");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("created_date");

                    b.Property<DateTime?>("DeletedDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("deleted_date");

                    b.Property<string>("DosyaYolu")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("dosya_yolu");

                    b.Property<int>("ProjeId")
                        .HasColumnType("int")
                        .HasColumnName("proje_id");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("updated_date");

                    b.HasKey("Id");

                    b.HasIndex("ProjeId");

                    b.ToTable("tbl_baptekniksartname", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Ad")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)")
                        .HasColumnName("ad");

                    b.Property<bool>("AktifMi")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true)
                        .HasColumnName("aktif_mi");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("created_date");

                    b.Property<DateTime?>("DeletedDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("deleted_date");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("email");

                    b.Property<string>("Soyad")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)")
                        .HasColumnName("soyad");

                    b.Property<string>("Telefon")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)")
                        .HasColumnName("telefon");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("updated_date");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("tbl_users", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.Yayin", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("created_date");

                    b.Property<DateTime?>("DeletedDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("deleted_date");

                    b.Property<string>("DergiAdi")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)")
                        .HasColumnName("dergi_adi");

                    b.Property<string>("Doi")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("doi");

                    b.Property<string>("DosyaYolu")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("dosya_yolu");

                    b.Property<int>("ProjeId")
                        .HasColumnType("int")
                        .HasColumnName("proje_id");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("updated_date");

                    b.Property<string>("YayinBasligi")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)")
                        .HasColumnName("yayin_basligi");

                    b.Property<DateTime?>("YayinTarihi")
                        .HasColumnType("datetime2")
                        .HasColumnName("yayin_tarihi");

                    b.HasKey("Id");

                    b.HasIndex("Doi");

                    b.HasIndex("ProjeId");

                    b.ToTable("tbl_bapyayin", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.BirimOnDegerlendirmeRaporu", b =>
                {
                    b.HasOne("Domain.Entities.BirimOnDegerlendirmeUyesi", "BirimOnDegerlendirmeUyesi")
                        .WithMany("Raporlar")
                        .HasForeignKey("KurulUyesiId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Domain.Entities.Proje", "Proje")
                        .WithMany()
                        .HasForeignKey("ProjeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("BirimOnDegerlendirmeUyesi");

                    b.Navigation("Proje");
                });

            modelBuilder.Entity("Domain.Entities.DetayliButce", b =>
                {
                    b.HasOne("Domain.Entities.Proje", "Proje")
                        .WithMany("DetayliButceler")
                        .HasForeignKey("ProjeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Proje");
                });

            modelBuilder.Entity("Domain.Entities.EkButceTalebi", b =>
                {
                    b.HasOne("Domain.Entities.Proje", "Proje")
                        .WithMany("EkButceTalepleri")
                        .HasForeignKey("ProjeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Proje");
                });

            modelBuilder.Entity("Domain.Entities.EkSureTalebi", b =>
                {
                    b.HasOne("Domain.Entities.Proje", "Proje")
                        .WithMany("EkSureTalepleri")
                        .HasForeignKey("ProjeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Proje");
                });

            modelBuilder.Entity("Domain.Entities.FormSorusu", b =>
                {
                    b.HasOne("Domain.Entities.FormSablonu", "FormSablonu")
                        .WithMany("Sorular")
                        .HasForeignKey("FormSablonuId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("FormSablonu");
                });

            modelBuilder.Entity("Domain.Entities.Harcama", b =>
                {
                    b.HasOne("Domain.Entities.Proje", "Proje")
                        .WithMany("Harcamalar")
                        .HasForeignKey("ProjeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Proje");
                });

            modelBuilder.Entity("Domain.Entities.KomisyonKarari", b =>
                {
                    b.HasOne("Domain.Entities.KomisyonUyesi", "KomisyonUyesi")
                        .WithMany("KomisyonKararlari")
                        .HasForeignKey("KomisyonUyesiId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Domain.Entities.Proje", "Proje")
                        .WithMany("KomisyonKararlari")
                        .HasForeignKey("ProjeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("KomisyonUyesi");

                    b.Navigation("Proje");
                });

            modelBuilder.Entity("Domain.Entities.ProformaFatura", b =>
                {
                    b.HasOne("Domain.Entities.Proje", "Proje")
                        .WithMany("ProformaFaturalar")
                        .HasForeignKey("ProjeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Proje");
                });

            modelBuilder.Entity("Domain.Entities.ProjeArastirmacisi", b =>
                {
                    b.HasOne("Domain.Entities.Proje", "Proje")
                        .WithMany("Arastirmacilar")
                        .HasForeignKey("ProjeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Proje");
                });

            modelBuilder.Entity("Domain.Entities.ProjeHakem", b =>
                {
                    b.HasOne("Domain.Entities.Hakem", "Hakem")
                        .WithMany("ProjeHakemleri")
                        .HasForeignKey("HakemId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Domain.Entities.Proje", "Proje")
                        .WithMany("ProjeHakemleri")
                        .HasForeignKey("ProjeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Hakem");

                    b.Navigation("Proje");
                });

            modelBuilder.Entity("Domain.Entities.ProjeRaporu", b =>
                {
                    b.HasOne("Domain.Entities.Proje", "Proje")
                        .WithMany("Raporlar")
                        .HasForeignKey("ProjeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Proje");
                });

            modelBuilder.Entity("Domain.Entities.SorunYaniti", b =>
                {
                    b.HasOne("Domain.Entities.SorunBildirimi", "SorunBildirimi")
                        .WithMany("Yanitlar")
                        .HasForeignKey("SorunBildirimiId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("SorunBildirimi");
                });

            modelBuilder.Entity("Domain.Entities.TeknikSartname", b =>
                {
                    b.HasOne("Domain.Entities.Proje", "Proje")
                        .WithMany("TeknikSartnameler")
                        .HasForeignKey("ProjeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Proje");
                });

            modelBuilder.Entity("Domain.Entities.Yayin", b =>
                {
                    b.HasOne("Domain.Entities.Proje", "Proje")
                        .WithMany("Yayinlar")
                        .HasForeignKey("ProjeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Proje");
                });

            modelBuilder.Entity("Domain.Entities.BirimOnDegerlendirmeUyesi", b =>
                {
                    b.Navigation("Raporlar");
                });

            modelBuilder.Entity("Domain.Entities.FormSablonu", b =>
                {
                    b.Navigation("Sorular");
                });

            modelBuilder.Entity("Domain.Entities.Hakem", b =>
                {
                    b.Navigation("ProjeHakemleri");
                });

            modelBuilder.Entity("Domain.Entities.KomisyonUyesi", b =>
                {
                    b.Navigation("KomisyonKararlari");
                });

            modelBuilder.Entity("Domain.Entities.Proje", b =>
                {
                    b.Navigation("Arastirmacilar");

                    b.Navigation("DetayliButceler");

                    b.Navigation("EkButceTalepleri");

                    b.Navigation("EkSureTalepleri");

                    b.Navigation("Harcamalar");

                    b.Navigation("KomisyonKararlari");

                    b.Navigation("ProformaFaturalar");

                    b.Navigation("ProjeHakemleri");

                    b.Navigation("Raporlar");

                    b.Navigation("TeknikSartnameler");

                    b.Navigation("Yayinlar");
                });

            modelBuilder.Entity("Domain.Entities.SorunBildirimi", b =>
                {
                    b.Navigation("Yanitlar");
                });
#pragma warning restore 612, 618
        }
    }
}
